### ISSUE TITLE
Scan PR code

### ISSUE THREAD

**Issue by ngowraj** [edplato/trufflehog-actions-scan#12]
Is it possible to just scan the PR code for secrets (rather than the entire repo code)? 

cc @edplato

**Comment by udplume** [comment]
@edplato I have a question on the same lines. It seems this action scans the entire repo / branch everytime. I was hoping the max_depth argument can be used to limit the scope of the scan. As an example tried the scan for a PR which only had the following commit as part of it.

<img width="1225" alt="TrufflehogActionTest" src="https://user-images.githubusercontent.com/49769547/123705814-45671700-d81c-11eb-9b3c-d54cca192c1b.png">

I understand that none of data in the above commit would have matched the "regexes". I had passed the argument for max_depth=1 and expected the check to pass. But the check reported a finding from a file which was already present in the branch but not part of this PR. As seen below . Is this expected. Is there a way to change this behavior ?

<img width="1257" alt="TrufflehogActionTest2" src="https://user-images.githubusercontent.com/49769547/123706017-90812a00-d81c-11eb-91a3-689b0d07d648.png">


Thank you

**Comment by edplato** [comment]
These questions are a little different, but let me try to address both with a precursor that trufflehog scans all branches unless a target branch is set (see https://github.com/trufflesecurity/truffleHog/pull/219#issuecomment-783685528).

 @ngowraj I haven't made any plans to implement this feature, but it should be possible by using the trufflehog options of `--since_commit` and the available GitHub actions environment variables. I welcome any PRs that address this.

@udplume Related to what I mentioned about scanning all branches, I believe the lack of a `--branch` argument is what is causing the issue with `--since_commit` not being applied as expected. On some local tests, I could narrow down the results I wanted by adding `--since_commit` and `--branch=MY_TARGET_BRANCH`. I plan on implementing the feature on an upcoming release that will use the current branch.

**Comment by udplume** [comment]
@edplato Thank you for looking into this. I tried using the following scanArguments through Github workflow and locally using a trufflehog on command line

Github Workflow 
"--regex --entropy=False --max_depth=1 --rules /regexes.json --branch ${{ github.head_ref }}"

The workflow is meant to be executed when a PR is opened from some branch onto the master. I do see that the checkout step gets the correct branch name and even the output produced by this trufflehog action indicates the "branch" which is the head for the PR. So I do think the correct branch is getting scanned . But adding the --branch parameter did not change anything in the output. The output for the above is the same as when only the below parameters are used in this workflow

"--regex --entropy=False  --rules /regexes.json "

Locally on commandline 
"--regex --entropy=False --max_depth=1 --rules /regexes.json --branch <branch_name>"

results in findings from just the last commit on that branch

You suggested using since_commit parameter. But I believe that requires a specific "commit sha" ? As I mentioned, my use case is to execute this on a PR event and in that case I am not sure how I can get the desired commit sha (in this case the most recent commit on the head of the PR) during runtime. Hence I was hoping to use the max_depth parameter so that the workflow also scans the most recent commit and not the entire branch everytime.

Do you have any suggestions on how to make it work ?

**Comment by edplato** [comment]
Look into latest https://github.com/edplato/trufflehog-actions-scan/pull/15 re: using `actions/checkout@v2` and the relationship of `max_depth` and `fetch-depth` to accomplish this.
